# Generated by Django 2.0.13 on 2023-10-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumb_nail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
