# Generated by Django 2.0.13 on 2023-10-16 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_thumb_nail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='invest_rate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='thumb_nail_des',
            field=models.TextField(blank=True, null=True),
        ),
    ]
