# Generated by Django 2.0.13 on 2023-10-18 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20231018_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='suss_rate',
            new_name='success_rate',
        ),
    ]
