# Generated by Django 2.0.13 on 2023-10-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20231018_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='MAX_LIMIT',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
