# Generated by Django 2.0.13 on 2023-10-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_apply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='APPLY_AMT',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='APPLY_DUE',
        ),
        migrations.AddField(
            model_name='apply',
            name='신청금액',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='apply',
            name='신청기간',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
