# Generated by Django 2.0.13 on 2023-10-20 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20231020_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='author',
        ),
    ]
